# Generated by Django 5.2.9 on 2026-01-04 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral_code', models.CharField(blank=True, max_length=32, unique=True)),
                ('inviter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitees', to='core.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('REF_BONUS', 'Referral bonus'), ('DAILY_ADD', 'Daily add locked'), ('DAILY_UNLOCK', 'Daily unlock'), ('BUY_PRINCIPAL', 'Buy principal locked'), ('BUY_SELF_PROFIT', 'Buy self profit locked'), ('SELF_PROFIT_UNLOCK', 'Self profit unlock'), ('PRINCIPAL_UNLOCK', 'Principal unlock'), ('DOWNLINE_PROFIT', 'Downline instant profit'), ('WITHDRAW', 'Withdraw')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=24)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='core.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=32, unique=True)),
                ('ton_amount', models.DecimalField(decimal_places=6, max_digits=24)),
                ('ton_tx_hash', models.CharField(max_length=256, unique=True)),
                ('ton_usd_rate', models.DecimalField(decimal_places=6, max_digits=24)),
                ('usd_value', models.DecimalField(decimal_places=6, max_digits=24)),
                ('ecg_value', models.DecimalField(decimal_places=6, max_digits=24)),
                ('self_profit_5', models.DecimalField(decimal_places=6, max_digits=24)),
                ('principal_unlock_at', models.DateTimeField()),
                ('self_profit_unlock_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='core.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_bonus', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('daily_reward_locked', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('daily_reward_unlocked', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('downline_profit_instant', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('self_profit_locked', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('self_profit_unlocked', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('principal_locked', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('principal_unlocked', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='core.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('DOWNLINE_ONLY', 'Downline only'), ('ALL_WITHDRAWABLE', 'All withdrawable')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=24)),
                ('destination_wallet', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraws', to='core.appuser')),
            ],
        ),
    ]
