# Generated by Django 5.2.9 on 2026-08-12 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('telegram_username', models.CharField(blank=True, help_text='یوزرنیم تلگرام کاربر', max_length=100, null=True)),
                ('wallet_address', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral_code', models.CharField(blank=True, max_length=32, unique=True)),
                ('next_daily_claim_at', models.DateTimeField(blank=True, null=True)),
                ('is_telegram_user', models.BooleanField(default=False)),
                ('telegram_verified', models.BooleanField(default=False)),
                ('wallet_locked', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False, help_text='آیا کاربر ادمین است؟')),
                ('is_active', models.BooleanField(default=True, help_text='آیا کاربر فعال است؟')),
                ('last_active', models.DateTimeField(blank=True, help_text='آخرین فعالیت کاربر', null=True)),
                ('total_investment', models.DecimalField(decimal_places=6, default=0, help_text='کل سرمایه\u200cگذاری', max_digits=24)),
                ('total_earned', models.DecimalField(decimal_places=6, default=0, help_text='کل سود کسب شده', max_digits=24)),
                ('inviter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitees', to='core.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('REF_BONUS', 'Referral bonus'), ('DAILY_ADD', 'Daily add locked'), ('DAILY_UNLOCK', 'Daily unlock'), ('BUY_PRINCIPAL', 'Buy principal locked'), ('BUY_SELF_PROFIT', 'Buy self profit locked'), ('SELF_PROFIT_UNLOCK', 'Self profit unlock'), ('PRINCIPAL_UNLOCK', 'Principal unlock'), ('DOWNLINE_PROFIT', 'Downline instant profit'), ('WITHDRAW', 'Withdraw'), ('LEVEL5_BONUS', 'Level 5 bonus')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=24)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='core.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=32, unique=True)),
                ('ton_amount', models.DecimalField(decimal_places=6, max_digits=24)),
                ('ton_tx_hash', models.CharField(max_length=256, unique=True)),
                ('ton_usd_rate', models.DecimalField(decimal_places=6, max_digits=24)),
                ('usd_value', models.DecimalField(decimal_places=6, max_digits=24)),
                ('ecg_value', models.DecimalField(decimal_places=6, max_digits=24)),
                ('self_profit_5', models.DecimalField(decimal_places=6, max_digits=24)),
                ('principal_unlock_at', models.DateTimeField()),
                ('self_profit_unlock_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='core.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseBNB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=32, unique=True)),
                ('bnb_amount', models.DecimalField(decimal_places=6, max_digits=24)),
                ('bnb_tx_hash', models.CharField(max_length=256, unique=True)),
                ('bnb_usd_rate', models.DecimalField(decimal_places=6, max_digits=24)),
                ('usd_value', models.DecimalField(decimal_places=6, max_digits=24)),
                ('ecg_value', models.DecimalField(decimal_places=6, max_digits=24)),
                ('self_profit_5', models.DecimalField(decimal_places=6, max_digits=24)),
                ('principal_unlock_at', models.DateTimeField()),
                ('self_profit_unlock_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_bnb', to='core.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseUSDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=32, unique=True)),
                ('usdt_amount', models.DecimalField(decimal_places=6, max_digits=24)),
                ('usdt_tx_hash', models.CharField(max_length=256, unique=True)),
                ('usdt_usd_rate', models.DecimalField(decimal_places=6, default=1, max_digits=24)),
                ('usd_value', models.DecimalField(decimal_places=6, max_digits=24)),
                ('ecg_value', models.DecimalField(decimal_places=6, max_digits=24)),
                ('self_profit_5', models.DecimalField(decimal_places=6, max_digits=24)),
                ('principal_unlock_at', models.DateTimeField()),
                ('self_profit_unlock_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_usdt', to='core.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_1_count', models.IntegerField(default=0)),
                ('level_2_count', models.IntegerField(default=0)),
                ('level_3_count', models.IntegerField(default=0)),
                ('level_4_count', models.IntegerField(default=0)),
                ('level_5_count', models.IntegerField(default=0)),
                ('level_1_users', models.JSONField(blank=True, default=list)),
                ('level_2_users', models.JSONField(blank=True, default=list)),
                ('level_3_users', models.JSONField(blank=True, default=list)),
                ('level_4_users', models.JSONField(blank=True, default=list)),
                ('level_5_users', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_level', to='core.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_bonus', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('daily_reward_locked', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('daily_reward_unlocked', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('downline_profit_instant', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('self_profit_locked', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('self_profit_unlocked', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('principal_locked', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('principal_unlocked', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level_profits', models.JSONField(default=dict)),
                ('total_deposited', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('total_withdrawn', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('last_withdraw_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='core.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('DOWNLINE_ONLY', 'Downline only'), ('ALL_WITHDRAWABLE', 'All withdrawable')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=24)),
                ('ton_amount', models.DecimalField(decimal_places=9, default=0, max_digits=24)),
                ('destination_wallet', models.CharField(max_length=128)),
                ('tx_hash', models.CharField(blank=True, default='', max_length=256)),
                ('fail_reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraws', to='core.appuser')),
            ],
        ),
    ]
