# Generated by Django 5.2.9 on 2026-08-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='telegram_photo_url',
            field=models.URLField(blank=True, help_text='آدرس آواتار تلگرام کاربر', max_length=1000, null=True),
        ),
    ]
