# Generated by Django 5.2.9 on 2026-01-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='next_daily_claim_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
