# Generated by Django 5.2.9 on 2026-08-15 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(choices=[('USDT', 'USDT')], max_length=8)),
                ('principal_locked', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('principal_unlocked', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('profit_locked', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('profit_unlocked', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_balances', to='core.appuser')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'asset'), name='unique_user_asset_balance')],
            },
        ),
    ]
