# Generated by Django 5.2.9 on 2026-02-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appuser_next_daily_claim_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='fail_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='source_wallet',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='tx_hash',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
