# Generated by Django 5.2.9 on 2026-02-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_withdrawrequest_fail_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawrequest',
            name='source_wallet',
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='ton_amount',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=16),
        ),
    ]
