# Generated by Django 5.2.9 on 2026-08-08 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_withdrawrequest_source_wallet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferraLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_1_count', models.IntegerField(default=0)),
                ('level_2_count', models.IntegerField(default=0)),
                ('level_3_count', models.IntegerField(default=0)),
                ('level_4_count', models.IntegerField(default=0)),
                ('level_5_count', models.IntegerField(default=0)),
                ('level_1_users', models.JSONField(blank=True, default=list)),
                ('level_2_users', models.JSONField(blank=True, default=list)),
                ('level_3_users', models.JSONField(blank=True, default=list)),
                ('level_4_users', models.JSONField(blank=True, default=list)),
                ('level_5_users', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_level', to='core.appuser')),
            ],
        ),
    ]
