# Generated by Django 5.2.9 on 2026-08-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_referralevel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReferraLevel',
            new_name='ReferralLevel',
        ),
        migrations.AlterField(
            model_name='ledger',
            name='typ',
            field=models.CharField(choices=[('REF_BONUS', 'Referral bonus'), ('DAILY_ADD', 'Daily add locked'), ('DAILY_UNLOCK', 'Daily unlock'), ('BUY_PRINCIPAL', 'Buy principal locked'), ('BUY_SELF_PROFIT', 'Buy self profit locked'), ('SELF_PROFIT_UNLOCK', 'Self profit unlock'), ('PRINCIPAL_UNLOCK', 'Principal unlock'), ('DOWNLINE_PROFIT', 'Downline instant profit'), ('WITHDRAW', 'Withdraw'), ('LEVEL5_BONUS', 'Level 5 bonus')], max_length=32),
        ),
    ]
