# Generated by Django 5.2.9 on 2026-08-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_referralevel_referrallevel_alter_ledger_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_telegram_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='telegram_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='level_profits',
            field=models.JSONField(default=dict),
        ),
    ]
