# Generated by Django 5.2.9 on 2026-08-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_appuser_is_telegram_user_appuser_telegram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='wallet_locked',
            field=models.BooleanField(default=False),
        ),
    ]
