# Generated by Django 5.2.9 on 2026-08-10 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_appuser_wallet_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBNB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=32, unique=True)),
                ('bnb_amount', models.DecimalField(decimal_places=6, max_digits=24)),
                ('bnb_tx_hash', models.CharField(max_length=256, unique=True)),
                ('bnb_usd_rate', models.DecimalField(decimal_places=6, max_digits=24)),
                ('usd_value', models.DecimalField(decimal_places=6, max_digits=24)),
                ('ecg_value', models.DecimalField(decimal_places=6, max_digits=24)),
                ('self_profit_5', models.DecimalField(decimal_places=6, max_digits=24)),
                ('principal_unlock_at', models.DateTimeField()),
                ('self_profit_unlock_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_bnb', to='core.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseUSDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=32, unique=True)),
                ('usdt_amount', models.DecimalField(decimal_places=6, max_digits=24)),
                ('usdt_tx_hash', models.CharField(max_length=256, unique=True)),
                ('usdt_usd_rate', models.DecimalField(decimal_places=6, default=1, max_digits=24)),
                ('usd_value', models.DecimalField(decimal_places=6, max_digits=24)),
                ('ecg_value', models.DecimalField(decimal_places=6, max_digits=24)),
                ('self_profit_5', models.DecimalField(decimal_places=6, max_digits=24)),
                ('principal_unlock_at', models.DateTimeField()),
                ('self_profit_unlock_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_usdt', to='core.appuser')),
            ],
        ),
    ]
