# Generated by Django 5.2.9 on 2026-08-11 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_purchasebnb_purchaseusdt'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('total_investment', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('new_investment', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('total_earnings', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('daily_earnings', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('total_payouts', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('daily_payouts', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('pending_payouts', models.IntegerField(default=0)),
                ('active_investments', models.IntegerField(default=0)),
                ('referral_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='total_earned',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='appuser',
            name='total_investment',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='purchase',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار'), ('CONFIRMED', 'تایید شده'), ('COMPLETED', 'تکمیل شده'), ('FAILED', 'ناموفق')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_withdraw_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_deposited',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_withdrawn',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=24),
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.appuser')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('VIEW_USER', 'مشاهده کاربر'), ('EDIT_USER', 'ویرایش کاربر'), ('LOCK_USER', 'قفل کاربر'), ('UNLOCK_USER', 'بازکردن قفل کاربر'), ('APPROVE_PAYOUT', 'تایید پرداخت'), ('REJECT_PAYOUT', 'رد پرداخت'), ('EDIT_INVESTMENT', 'ویرایش سرمایه گذاری'), ('VIEW_REPORT', 'مشاهده گزارش'), ('EXPORT_DATA', 'خروجی گرفتن')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to='core.appuser')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_actions', to='core.appuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user', 'created_at'], name='core_admina_admin_u_1f153c_idx'), models.Index(fields=['action_type'], name='core_admina_action__6689b3_idx')],
            },
        ),
    ]
