# Generated by Django 5.2.9 on 2026-08-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_dailystats_appuser_is_active_appuser_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminactionlog',
            name='admin_user',
        ),
        migrations.RemoveField(
            model_name='adminactionlog',
            name='target_user',
        ),
        migrations.DeleteModel(
            name='DailyStats',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='last_active',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='total_earned',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='total_investment',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='admin_note',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='status',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='last_withdraw_at',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='total_deposited',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='total_withdrawn',
        ),
        migrations.DeleteModel(
            name='AdminActionLog',
        ),
        migrations.DeleteModel(
            name='SystemSettings',
        ),
    ]
